# Generated by Django 4.1.2 on 2022-11-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
