# Generated by Django 4.1.2 on 2022-11-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0002_alter_persona_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
