# Generated by Django 4.1.2 on 2022-11-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_app', '0003_persona_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='precio',
            new_name='valor',
        ),
    ]
